import type {
  ActionTemplate,
  Catalog,
  ConversionTemplate,
  MachineBlueprint,
  ModuleDefinition,
  PresetDefinition,
} from "../sim/types";

/*
 * Content is deliberately declarative.  The objects below contain no callbacks
 * or executable user formulas; the simulation only accepts these known
 * templates and bounded parameters.
 */

const templates: Record<string, ConversionTemplate> = {
  photosynthesis: {
    id: "photosynthesis",
    kind: "growth",
    inputMass: { water: 1, nutrient: 1 },
    structureOutput: 2,
    edibleOutput: 1,
    chemicalInput: 2,
    storedOutput: 1,
    heatOutput: 1,
    integrityOutput: 1,
    maxStructureOutput: 2,
    rate: 1,
  },
  digestion: {
    id: "digestion",
    kind: "digestion",
    inputFood: 1,
    chemicalInput: 2,
    storedOutput: 1,
    heatOutput: 1,
    wasteOutput: 1,
    rate: 1,
  },
  charge: {
    id: "charge",
    kind: "charge",
    storedInput: 4,
    chargeOutput: 3,
    heatOutput: 1,
    rate: 1,
  },
  discharge: {
    id: "discharge",
    kind: "discharge",
    chargeInput: 3,
    heatOutput: 3,
    rate: 1,
  },
  burn: {
    id: "burn",
    kind: "burn",
    fuelInput: 1,
    chemicalInput: 2,
    heatOutput: 2,
    structuralDamage: 1,
    scrapOutput: 1,
    rate: 1,
  },
  raw_to_product: {
    id: "raw_to_product",
    kind: "process",
    rawInput: 1,
    productOutput: 1,
    storedInput: 2,
    heatOutput: 2,
    rate: 1,
  },
};

const actions: Record<string, ActionTemplate> = {
  move_ground: { id: "move_ground", kind: "move", storedCost: 1, rate: 1 },
  move_air: { id: "move_air", kind: "move", storedCost: 2, rate: 1 },
  predation_work: { id: "predation_work", kind: "work_damage", storedCost: 1, damage: 2, rate: 1 },
};

const modules: Record<string, ModuleDefinition> = {
  organic_tissue: {
    semanticId: "organic_tissue",
    display: "🌿",
    shortLabel: "유기 조직",
    requiredSlotsOrPorts: [{ id: "heat-in", kind: "heat", direction: "in" }],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 1,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 1,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 4,
        raw: 0,
        product: 0,
        scrap: 8,
        waste: 8,
      },
      energy: { stored: 0, charge: 0, chemical: 0, heat: 8 },
    },
    maintenanceCost: { stored: 0 },
    providedCapabilities: ["flammable", "edible_tissue"],
    referencedActionOrConversionTemplateIds: ["burn"],
    boundedParameters: { heatCapacity: 8 },
    activation: "automatic",
    exclusiveSlot: "body",
  },
  photosynthesis_module: {
    semanticId: "photosynthesis_module",
    display: "☀️",
    shortLabel: "광합성 기관",
    requiredSlotsOrPorts: [
      { id: "water-in", kind: "mass", direction: "in" },
      { id: "nutrient-in", kind: "mass", direction: "in" },
      { id: "light-in", kind: "energy", direction: "in" },
    ],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 1,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 1,
    resourceCapacities: {
      mass: {
        water: 4,
        nutrient: 4,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      energy: { stored: 6, charge: 0, chemical: 12, heat: 8 },
    },
    maintenanceCost: { stored: 0 },
    providedCapabilities: ["photosynthesize"],
    referencedActionOrConversionTemplateIds: ["photosynthesis"],
    boundedParameters: { lightRate: 2 },
    activation: "automatic",
    exclusiveSlot: "metabolism",
  },
  ground_locomotion: {
    semanticId: "ground_locomotion",
    display: "🦶",
    shortLabel: "지상 이동",
    requiredSlotsOrPorts: [{ id: "control", kind: "control", direction: "bidirectional" }],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 1,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 1,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      energy: { stored: 6, charge: 0, chemical: 0, heat: 4 },
    },
    maintenanceCost: { stored: 0 },
    providedCapabilities: ["ground_move"],
    referencedActionOrConversionTemplateIds: ["move_ground"],
    boundedParameters: { groundMoveCost: 1 },
    activation: "intent",
    exclusiveSlot: "locomotion",
  },
  herbivore_digestion: {
    semanticId: "herbivore_digestion",
    display: "🥕",
    shortLabel: "식물 소화 기관",
    requiredSlotsOrPorts: [{ id: "food-in", kind: "mass", direction: "in" }],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 1,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 1,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 4,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 8,
      },
      energy: { stored: 6, charge: 0, chemical: 0, heat: 4 },
    },
    maintenanceCost: { stored: 1 },
    providedCapabilities: ["digest_food", "consume_plant"],
    referencedActionOrConversionTemplateIds: ["digestion"],
    boundedParameters: { foodCapacity: 4 },
    activation: "automatic",
    exclusiveSlot: "digestion",
  },
  predator_digestion: {
    semanticId: "predator_digestion",
    display: "🦷",
    shortLabel: "동물 소화·작업 기관",
    requiredSlotsOrPorts: [{ id: "food-in", kind: "mass", direction: "in" }],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 1,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 1,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 4,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 8,
        waste: 8,
      },
      energy: { stored: 6, charge: 0, chemical: 0, heat: 4 },
    },
    maintenanceCost: { stored: 1 },
    providedCapabilities: ["digest_food", "consume_animal", "work_damage"],
    referencedActionOrConversionTemplateIds: ["digestion", "predation_work"],
    boundedParameters: { foodCapacity: 4, workDamage: 2 },
    activation: "automatic",
    exclusiveSlot: "digestion",
  },
  wing_lift: {
    semanticId: "wing_lift",
    display: "🪽",
    shortLabel: "양력 기관",
    requiredSlotsOrPorts: [{ id: "control", kind: "control", direction: "bidirectional" }],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 2,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 2,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      energy: { stored: 8, charge: 0, chemical: 0, heat: 6 },
    },
    maintenanceCost: { stored: 1 },
    providedCapabilities: ["lift", "air_move"],
    referencedActionOrConversionTemplateIds: ["move_air"],
    boundedParameters: { liftCapacity: 12, flightMaintenance: 1, airMoveCost: 2 },
    activation: "intent",
    exclusiveSlot: "lift",
  },
  electric_storage: {
    semanticId: "electric_storage",
    display: "⚡",
    shortLabel: "전하 저장소",
    requiredSlotsOrPorts: [
      { id: "energy-in", kind: "energy", direction: "in" },
      { id: "energy-out", kind: "energy", direction: "out" },
    ],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 1,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 1,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 4,
        waste: 4,
      },
      energy: { stored: 0, charge: 12, chemical: 0, heat: 4 },
    },
    maintenanceCost: { stored: 0 },
    providedCapabilities: ["charge_storage", "electric_discharge"],
    referencedActionOrConversionTemplateIds: ["charge", "discharge"],
    boundedParameters: { chargeRate: 3, dischargeRate: 3 },
    activation: "intent",
    exclusiveSlot: "energy",
  },
  night_sense: {
    semanticId: "night_sense",
    display: "🌙",
    shortLabel: "야간 감각",
    requiredSlotsOrPorts: [],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 1,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 1,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      energy: { stored: 0, charge: 0, chemical: 0, heat: 2 },
    },
    maintenanceCost: { stored: 0 },
    providedCapabilities: ["night_sense"],
    referencedActionOrConversionTemplateIds: [],
    boundedParameters: { darkRange: 4 },
    activation: "automatic",
    exclusiveSlot: "sense",
  },
  storage_bin: {
    semanticId: "storage_bin",
    display: "📦",
    shortLabel: "원료·제품 저장소",
    requiredSlotsOrPorts: [
      { id: "raw-out", kind: "mass", direction: "out" },
      { id: "product-in", kind: "mass", direction: "in" },
      { id: "energy-out", kind: "energy", direction: "out" },
      { id: "heat-in", kind: "heat", direction: "in" },
    ],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 2,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 2,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 6,
        product: 6,
        scrap: 4,
        waste: 4,
      },
      energy: { stored: 0, charge: 0, chemical: 0, heat: 10 },
    },
    maintenanceCost: { stored: 0 },
    providedCapabilities: ["storage"],
    referencedActionOrConversionTemplateIds: [],
    boundedParameters: { rawCapacity: 6, productCapacity: 6 },
    activation: "automatic",
    exclusiveSlot: "storage",
  },
  processor: {
    semanticId: "processor",
    display: "⚙️",
    shortLabel: "기존 변환 가공기",
    requiredSlotsOrPorts: [
      { id: "raw-in", kind: "mass", direction: "in" },
      { id: "product-out", kind: "mass", direction: "out" },
      { id: "energy-in", kind: "energy", direction: "in" },
      { id: "heat-out", kind: "heat", direction: "out" },
    ],
    materialCost: {
      water: 0,
      nutrient: 0,
      organic: 2,
      food: 0,
      fuel: 0,
      raw: 0,
      product: 0,
      scrap: 0,
      waste: 0,
    },
    structuralMass: 2,
    resourceCapacities: {
      mass: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 4,
        waste: 4,
      },
      energy: { stored: 0, charge: 0, chemical: 0, heat: 8 },
    },
    maintenanceCost: { stored: 1 },
    providedCapabilities: ["process", "automatic_machine"],
    referencedActionOrConversionTemplateIds: ["raw_to_product"],
    boundedParameters: { processRate: 1 },
    activation: "automatic",
  },
};

const baseCapacities = {
  mass: {
    water: 0,
    nutrient: 0,
    organic: 0,
    food: 0,
    fuel: 0,
    raw: 0,
    product: 0,
    scrap: 0,
    waste: 0,
  },
  energy: { stored: 12, charge: 0, chemical: 12, heat: 12 },
};

const presets: Record<string, PresetDefinition> = {
  plant: {
    semanticId: "plant",
    display: "🌿",
    shortLabel: "식물",
    kind: "plant",
    moduleIds: ["organic_tissue", "photosynthesis_module"],
    base: {
      structureMass: 4,
      maxStructureMass: 8,
      integrity: 6,
      maxIntegrity: 6,
      edibleMass: 3,
      energy: { stored: 0, charge: 0, chemical: 6, heat: 0 },
      inventory: {
        water: 3,
        nutrient: 3,
        organic: 0,
        food: 0,
        fuel: 3,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      heatCapacity: 20,
      resourceCapacities: baseCapacities,
      maintenanceCost: 0,
      maintenanceFailureDamage: 1,
    },
    capabilities: [],
    movement: { mode: "stationary", groundCost: 0, airCost: 0, maxDistancePerStep: 0 },
    senses: { dayRange: 0, darkRange: 0 },
    nutrition: {
      preference: [],
      edibleAs: "plant_tissue",
      foodAccess: "alive",
      foodCapacity: 0,
    },
    combustion: {
      enabled: true,
      fuelResource: "fuel",
      ignitionTemperature: 4,
      fuelPerStep: 1,
      chemicalEnergyPerFuel: 2,
      heatPerFuel: 2,
      damagePerStep: 1,
    },
  },
  herbivore: {
    semanticId: "herbivore",
    display: "🐇",
    shortLabel: "초식동물",
    kind: "creature",
    moduleIds: ["organic_tissue", "ground_locomotion", "herbivore_digestion"],
    base: {
      structureMass: 3,
      maxStructureMass: 3,
      integrity: 5,
      maxIntegrity: 5,
      edibleMass: 2,
      energy: { stored: 3, charge: 0, chemical: 4, heat: 0 },
      inventory: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      heatCapacity: 16,
      resourceCapacities: baseCapacities,
      maintenanceCost: 1,
      maintenanceFailureDamage: 1,
    },
    capabilities: [],
    movement: { mode: "ground", groundCost: 1, airCost: 2, maxDistancePerStep: 1 },
    senses: { dayRange: 4, darkRange: 1 },
    nutrition: {
      preference: ["plant_tissue"],
      edibleAs: "animal_tissue",
      foodAccess: "after_death",
      digestionTemplateId: "digestion",
      foodCapacity: 4,
    },
    combustion: {
      enabled: false,
      fuelResource: "fuel",
      ignitionTemperature: 999,
      fuelPerStep: 0,
      chemicalEnergyPerFuel: 0,
      heatPerFuel: 0,
      damagePerStep: 0,
    },
  },
  predator: {
    semanticId: "predator",
    display: "🐺",
    shortLabel: "포식자",
    kind: "creature",
    moduleIds: ["organic_tissue", "ground_locomotion", "predator_digestion"],
    base: {
      structureMass: 4,
      maxStructureMass: 4,
      integrity: 6,
      maxIntegrity: 6,
      edibleMass: 3,
      energy: { stored: 4, charge: 0, chemical: 6, heat: 0 },
      inventory: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      heatCapacity: 18,
      resourceCapacities: baseCapacities,
      maintenanceCost: 1,
      maintenanceFailureDamage: 1,
    },
    capabilities: [],
    movement: { mode: "ground", groundCost: 1, airCost: 2, maxDistancePerStep: 1 },
    senses: { dayRange: 5, darkRange: 1 },
    nutrition: {
      preference: ["animal_tissue"],
      edibleAs: "animal_tissue",
      foodAccess: "after_death",
      digestionTemplateId: "digestion",
      foodCapacity: 4,
    },
    combustion: {
      enabled: false,
      fuelResource: "fuel",
      ignitionTemperature: 999,
      fuelPerStep: 0,
      chemicalEnergyPerFuel: 0,
      heatPerFuel: 0,
      damagePerStep: 0,
    },
  },
  fuel_crate: {
    semanticId: "fuel_crate",
    display: "🪵",
    shortLabel: "가연성 잔해",
    kind: "machine",
    moduleIds: ["organic_tissue"],
    base: {
      structureMass: 2,
      maxStructureMass: 2,
      integrity: 2,
      maxIntegrity: 2,
      edibleMass: 0,
      energy: { stored: 0, charge: 0, chemical: 8, heat: 0 },
      inventory: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 4,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      heatCapacity: 12,
      resourceCapacities: baseCapacities,
      maintenanceCost: 0,
      maintenanceFailureDamage: 0,
    },
    capabilities: [],
    movement: { mode: "stationary", groundCost: 0, airCost: 0, maxDistancePerStep: 0 },
    senses: { dayRange: 0, darkRange: 0 },
    nutrition: { preference: [], foodAccess: "after_death", foodCapacity: 0 },
    combustion: {
      enabled: true,
      fuelResource: "fuel",
      ignitionTemperature: 4,
      fuelPerStep: 1,
      chemicalEnergyPerFuel: 2,
      heatPerFuel: 2,
      damagePerStep: 1,
    },
  },
  fragile_prey: {
    semanticId: "fragile_prey",
    display: "🪶",
    shortLabel: "취약한 먹이",
    kind: "creature",
    moduleIds: ["organic_tissue"],
    base: {
      structureMass: 1,
      maxStructureMass: 1,
      integrity: 1,
      maxIntegrity: 1,
      edibleMass: 1,
      energy: { stored: 0, charge: 0, chemical: 2, heat: 0 },
      inventory: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      heatCapacity: 8,
      resourceCapacities: baseCapacities,
      maintenanceCost: 0,
      maintenanceFailureDamage: 1,
    },
    capabilities: [],
    movement: { mode: "stationary", groundCost: 0, airCost: 0, maxDistancePerStep: 0 },
    senses: { dayRange: 0, darkRange: 0 },
    nutrition: { preference: [], edibleAs: "animal_tissue", foodAccess: "after_death", foodCapacity: 0 },
    combustion: {
      enabled: false,
      fuelResource: "fuel",
      ignitionTemperature: 999,
      fuelPerStep: 0,
      chemicalEnergyPerFuel: 0,
      heatPerFuel: 0,
      damagePerStep: 0,
    },
  },
  fragile_predator: {
    semanticId: "fragile_predator",
    display: "🦊",
    shortLabel: "취약한 포식자",
    kind: "creature",
    moduleIds: ["organic_tissue", "ground_locomotion", "predator_digestion"],
    base: {
      structureMass: 1,
      maxStructureMass: 1,
      integrity: 1,
      maxIntegrity: 1,
      edibleMass: 1,
      energy: { stored: 3, charge: 0, chemical: 4, heat: 0 },
      inventory: {
        water: 0,
        nutrient: 0,
        organic: 0,
        food: 0,
        fuel: 0,
        raw: 0,
        product: 0,
        scrap: 0,
        waste: 0,
      },
      heatCapacity: 12,
      resourceCapacities: baseCapacities,
      maintenanceCost: 1,
      maintenanceFailureDamage: 1,
    },
    capabilities: [],
    movement: { mode: "ground", groundCost: 1, airCost: 2, maxDistancePerStep: 1 },
    senses: { dayRange: 3, darkRange: 1 },
    nutrition: { preference: ["animal_tissue"], edibleAs: "animal_tissue", foodAccess: "after_death", digestionTemplateId: "digestion", foodCapacity: 4 },
    combustion: {
      enabled: false,
      fuelResource: "fuel",
      ignitionTemperature: 999,
      fuelPerStep: 0,
      chemicalEnergyPerFuel: 0,
      heatPerFuel: 0,
      damagePerStep: 0,
    },
  },
};

const machines: Record<string, MachineBlueprint> = {
  recycler: {
    semanticId: "recycler",
    display: "📦⚙️",
    shortLabel: "원료 가공 기계",
    modules: [
      { alias: "storage", definitionId: "storage_bin" },
      { alias: "processor", definitionId: "processor" },
    ],
    connections: [
      {
        id: "raw-feed",
        from: { alias: "storage", portId: "raw-out" },
        to: { alias: "processor", portId: "raw-in" },
        kind: "mass",
        rate: 1,
      },
      {
        id: "product-return",
        from: { alias: "processor", portId: "product-out" },
        to: { alias: "storage", portId: "product-in" },
        kind: "mass",
        rate: 1,
      },
      {
        id: "work-energy",
        from: { alias: "storage", portId: "energy-out" },
        to: { alias: "processor", portId: "energy-in" },
        kind: "energy",
        rate: 1,
      },
      {
        id: "waste-heat",
        from: { alias: "processor", portId: "heat-out" },
        to: { alias: "storage", portId: "heat-in" },
        kind: "heat",
        rate: 1,
      },
    ],
  },
};

export const DEFAULT_CATALOG: Catalog = { templates, actions, modules, presets, machines };
